# -*- coding: utf-8 -*-
"""Append missing *_kh string resources for Wanderlust."""
from __future__ import annotations

import re
from pathlib import Path

XML = Path(__file__).resolve().parents[1] / "app/src/main/res/values/strings.xml"

# Manual Khmer translations for every base key missing *_kh
KH: dict[str, str] = {
    "app_name": "Wanderlust",
    "welcome_badge": "ដំណើរផ្សងព្រេងថ្មីកំពុងរង់ចាំ",
    "welcome_subtitle": "ស្វែងរកប្រាសាទ ឆ្នេរ ភ្នំ និងម្ហូបនៅទូទាំងកម្ពុជា។ ដំណើរផ្សងព្រេងបន្ទាប់របស់អ្នកចាប់ផ្តើមនៅទីនេះ។",
    "welcome_or_connect": "ឬភ្ជាប់ជាមួយ",
    "welcome_stat_explorers": "អ្នកធ្វើដំណើរ",
    "welcome_stat_rating": "ការវាយតម្លៃ",
    "btn_get_started": "ចាប់ផ្តើម",
    "already_have_account": "មានគណនីរួចហើយ?",
    "btn_login": "ចូល",
    "btn_register": "ចុះឈ្មោះ",
    "welcome_option_hint": "សូមជ្រើស ចូល ឬ ចុះឈ្មោះ",
    "login_title": "សូមស្វាគមន៍មកវិញ",
    "login_subtitle": "បញ្ចូលព័ត៌មានដើម្បីចូលគណនី។",
    "login_hint": "សាកល្បង: user@test.com / 123456 ឬ admin@test.com / admin123",
    "login_fill_test_user": "បំពេញអ្នកប្រើសាកល្បង",
    "login_fill_test_admin": "បំពេញ admin សាកល្បង",
    "label_email": "អ៊ីមែល",
    "label_password": "ពាក្យសម្ងាត់",
    "label_name": "ឈ្មោះពេញ",
    "register_title": "បង្កើតគណនី",
    "btn_create_account": "បង្កើតគណនី",
    "home_adventure_label": "ដំណើរផ្សងព្រេងកំពុងរង់ចាំ",
    "brand_tagline": "សម្រេចជិតអ្នក · ស្វែងយល់កម្ពុជា",
    "home_more_places": "កន្លែងបន្ថែម %1$d",
    "home_explore_categories": "រុករកតាមប្រភេទ",
    "home_popular_destinations": "ទិសដៅពេញនិយម",
    "home_view_all": "មើលទាំងអស់",
    "explore_offline_hint": "កម្មវិធីសាកល្បង USB, emulator, រួច Wi‑Fi ដោយស្វ័យប្រវត្តិ។ ចាប់ផ្តើម backend (npm start)។",
    "explore_sample_tours": "ទេសចរណ៍គំរូ (អូហ្វឡាញ)",
    "profile_tier": "អ្នករុករកមាស",
    "profile_bookings": "ផែនការរក្សាទុក",
    "profile_help": "មជ្ឈមណ្ឌលជំនួយ",
    "profile_logout": "ចាកចេញ",
    "nearby_you_marker": "អ្នកនៅទីនេះ",
    "nearby_need_permission": "អនុញ្ញាតទីតាំងដើម្បីមើលកន្លែងជិតខាងលើផែនទី។",
    "nearby_enable_location": "បើកទីតាំង",
    "nearby_permission_denied": "ការអនុញ្ញាតទីតាំងត្រូវបានបដិសេធ។ អាចបើកក្នុងការកំណត់ប្រព័ន្ធ។",
    "nearby_location_unavailable": "មិនអាចអានទីតាំងបច្ចុប្បន្ន។ សាកម្តងទៀតនៅក្រៅ ឬបើក GPS។",
    "nearby_finding": "កំពុងរកទីតាំងរបស់អ្នក…",
    "nearby_requesting_permission": "កំពុងរង់ចាំការអនុញ្ញាតទីតាំង…",
    "nearby_open_settings": "បើកការកំណត់កម្មវិធី",
    "nearby_try_permission_again": "អនុញ្ញាតទីតាំង",
    "nearby_loading_places": "កំពុងផ្ទុកកន្លែងជិតខាង…",
    "nearby_results_count": "កន្លែង %1$d នៅជិតអ្នក",
    "nearby_disabled_settings": "សេវាទីតាំងត្រូវបានបិទក្នុងការកំណត់។",
    "nearby_quick_needs": "ត្រូវការអ្វី?",
    "nearby_more_categories": "ប្រភេទបន្ថែម",
    "nearby_radius_label": "ចម្ងាយ",
    "nearby_radius_500": "ដើរ ៥០០ ម",
    "nearby_radius_1000": "១ គម",
    "nearby_radius_2000": "២ គម",
    "nearby_radius_5000": "៥ គម",
    "nearby_radius_10000": "១០ គម",
    "nearby_sort_nearest": "ជិតបំផុត",
    "nearby_sort_top_rated": "ពេញនិយមខ្ពស់",
    "nearby_open_now": "បើកឥឡូវ",
    "nearby_directions": "ទិសដៅ",
    "nearby_call": "ហៅ",
    "nearby_save": "រក្សាទុក",
    "nearby_saved": "បានរក្សាទុក",
    "nearby_status_open": "បើក",
    "nearby_status_closed": "បិទ",
    "nearby_sign_in_to_save": "ចូលគណនីដើម្បីរក្សាទុកកន្លែង",
    "nearby_search_clear": "សម្អាតការស្វែងរក",
    "nearby_tap_for_details": "ចុចមើលលម្អិត",
    "nearby_detail_address": "អាសយដ្ឋាន",
    "nearby_detail_phone": "ទូរស័ព្ទ",
    "nearby_detail_coords": "កូអរដោនេ: %1$s, %2$s",
    "nearby_detail_close": "បិទ",
    "nearby_reviews_count": "វាយតម្លៃ %1$d",
    "nearby_right_now": "ឥឡូវនេះ",
    "nearby_moment_morning_cafe": "ហាងកាហ្វេ / អាហារពេលព្រឹក",
    "nearby_moment_morning_bakery": "ហាងនំ",
    "nearby_moment_midday_food": "អាហារថ្ងៃត្រង់ជិតខាង",
    "nearby_moment_midday_atm": "ត្រូវការសាច់ប្រាក់",
    "nearby_moment_evening_food": "អាហារពេលល្ងាច",
    "nearby_moment_evening_pharmacy": "ឱសថស្ថាន",
    "nearby_moment_late_convenience": "ហាងបើកយប់",
    "nearby_moment_late_gas": "ស្ថានីយ៍ប្រេង",
    "nearby_moment_open_now": "បើកឥឡូវនៅជិតខ្ញុំ",
    "nearby_moment_emergency": "អាសន្ន / មន្ទីរពេទ្យ",
    "nearby_best_pick": "ជ្រើសរើសល្អបំផុត",
    "nearby_best_reason_open": "បើកជិតបំផុត · ★%1$s · %2$s",
    "nearby_best_reason_nearby": "ត្រូវគ្នាល្អ · ★%1$s · %2$s",
    "nearby_best_reason_closed": "វាយតម្លៃខ្ពស់ជិតខាង · ★%1$s · %2$s",
    "nearby_compare_title": "ប្រៀបធៀបរហ័ស",
    "nearby_walk_min": "ដើរ ~%1$d នាទី",
    "nearby_copy_address": "ចម្លងអាសយដ្ឋាន",
    "nearby_share": "ចែករំលែក",
    "nearby_copied": "បានចម្លងអាសយដ្ឋាន",
    "nearby_recent": "បានមើលថ្មីៗ",
    "nearby_share_text": "%1$s\n%2$s\n%3$s",
    "btn_admin": "ផ្ទាំងគ្រប់គ្រង Admin",
    "btn_retry": "ព្យាយាមម្តងទៀត",
    "btn_search": "ស្វែងរក",
    "explore_no_results": "មិនមានកន្លែងត្រូវនឹងការស្វែងរក។ សាកពាក្យគន្លឹះ ឬប្រភេទផ្សេង។",
    "saved_empty": "មិនទាន់មានកន្លែងរក្សាទុក។ រក្សាទុកកន្លែងណែនាំ ឬបន្ថែមផ្ទាល់។",
    "btn_add_your_place": "បន្ថែមកន្លែងរបស់អ្នក",
    "add_saved_place_title": "បន្ថែមកន្លែងទៅបញ្ជី",
    "add_saved_place_hint": "រក្សាទុកកន្លែងដែលចង់ទៅ៖ បញ្ចូលព័ត៌មាន បើក Google Maps រួចបិទភ្ជាប់តំណ ឬកូអរដោនេ។",
    "label_place_name": "ឈ្មោះកន្លែង",
    "label_place_address": "អាសយដ្ឋាន / តំបន់",
    "label_place_notes": "កំណត់ចំណាំ (ជម្រើស)",
    "label_maps_link": "តំណ Google Maps (ជម្រើស)",
    "hint_maps_link": "តំណចែករំលែកពី Maps ឧ. maps.google.com/…",
    "label_latitude": "រយៈទទឹង (ជម្រើស)",
    "label_longitude": "រយៈបណ្តោយ (ជម្រើស)",
    "btn_open_google_maps": "ស្វែងរកលើ Google Maps",
    "btn_save_to_my_list": "រក្សាទុកក្នុងបញ្ជី",
    "admin_title": "ផ្ទាំងគ្រប់គ្រង Admin",
    "admin_tours_count": "កន្លែងណែនាំ: %1$d",
    "admin_users_count": "អ្នកប្រើ: %1$d",
    "admin_export_title": "នាំចេញទិន្នន័យ",
    "btn_back": "ថយក្រោយ",
    "login_sign_up_prompt": "មិនទាន់មានគណនី? ចុះឈ្មោះ",
    "register_sign_in_prompt": "មានគណនីរួចហើយ? ចូល",
    "placeholder_desc": "ផ្នែកនេះតាមការរចនា។ ទម្រង់ពេញលេញអាចបន្ថែមនៅពេលក្រោយ។",
    "saved_plan_title": "កន្លែងរក្សាទុក",
    "saved_plan_sample_name": "អង្គរវត្ត",
    "saved_plan_ref": "រក្សាទុក · WL-88942",
    "saved_plan_location": "សៀមរាប កម្ពុជា",
    "btn_go_home": "ទៅទំព័រដើម",
    "language_english": "English",
    "language_khmer": "ភាសាខ្មែរ",
    "nav_menu": "ម៉ឺនុយ",
    "tours_filter_rating": "★ ៤+",
    "label_transmission": "ប្រអប់លេខ",
    "label_fuel": "ប្រេងឥន្ធនៈ",
    "tips_count": "ណែនាំ %1$d",
    "guest_banner_body": "អ្នកកំពុងមើល %1$d ក្នុងចំណោម %2$d កន្លែង។ បង្កើតគណនីឥតគិតថ្លៃសម្រាប់បញ្ជីពេញលេញ រក្សាទុក និងធ្វើសមកាលកម្ម។",
    "guest_banner_sign_in": "ចូល ឬ ចុះឈ្មោះ",
    "forgot_password_link": "ភ្លេចពាក្យសម្ងាត់?",
    "forgot_password_title": "ភ្លេចពាក្យសម្ងាត់",
    "forgot_password_subtitle": "បញ្ចូលអ៊ីមែល។ យើងនឹងផ្តល់លេខកូដកំណត់ឡើងវិញក្នុងកម្មវិធី (មានសុពលភាព ១ ម៉ោង)។",
    "forgot_password_code": "លេខកូដរបស់អ្នក: %1$s",
    "btn_send_reset_code": "ផ្ញើលេខកូដ",
    "btn_enter_new_password": "បញ្ចូលពាក្យសម្ងាត់ថ្មី",
    "reset_password_title": "កំណត់ពាក្យសម្ងាត់ថ្មី",
    "label_reset_code": "លេខកូដកំណត់ឡើងវិញ",
    "label_new_password": "ពាក្យសម្ងាត់ថ្មី",
    "label_confirm_password": "បញ្ជាក់ពាក្យសម្ងាត់",
    "label_current_password": "ពាក្យសម្ងាត់បច្ចុប្បន្ន",
    "btn_reset_password": "ធ្វើបច្ចុប្បន្នភាពពាក្យសម្ងាត់",
    "change_password_title": "ផ្លាស់ប្តូរពាក្យសម្ងាត់",
    "btn_change_password": "រក្សាទុកពាក្យសម្ងាត់ថ្មី",
    "settings_change_password": "ផ្លាស់ប្តូរពាក្យសម្ងាត់",
    "settings_change_password_sub": "ធ្វើបច្ចុប្បន្នភាពពាក្យសម្ងាត់ចូល",
    "profile_guest_title": "មើលជាភ្ញៀវ",
    "profile_guest_subtitle": "ចូលដើម្បីមើលកន្លែងទាំងអស់ និងបញ្ជីរក្សាទុក",
    "profile_section_account": "គណនី",
    "profile_section_support": "ជំនួយ",
    "profile_section_legal": "ផ្លូវច្បាប់",
    "profile_section_app": "កម្មវិធី",
    "profile_edit": "កែប្រវត្តិរូប",
    "profile_edit_sub": "ឈ្មោះ ទូរស័ព្ទ ទីក្រុង របៀបធ្វើដំណើរ និងច្រើនទៀត",
    "profile_change_password": "ផ្លាស់ប្តូរពាក្យសម្ងាត់",
    "profile_change_password_sub": "ធ្វើបច្ចុប្បន្នភាពពាក្យសម្ងាត់ចូល",
    "edit_profile_title": "កែប្រវត្តិរូប",
    "edit_profile_your_name": "ឈ្មោះរបស់អ្នក",
    "edit_profile_section_personal": "ព័ត៌មានផ្ទាល់ខ្លួន",
    "edit_profile_section_travel": "ចំណូលចិត្តធ្វើដំណើរ",
    "edit_profile_section_account": "ព័ត៌មានគណនី",
    "edit_profile_section_security": "សុវត្ថិភាព",
    "label_account_type": "ប្រភេទគណនី",
    "account_type_user": "អ្នកធ្វើដំណើរ",
    "account_type_admin": "អ្នកគ្រប់គ្រង",
    "edit_profile_name_invalid": "សូមបញ្ចូលឈ្មោះពេញ មិនមែនអ៊ីមែល",
    "edit_profile_photo_hint": "រូបតំណាងប្រើអក្សរដើមឈ្មោះ",
    "edit_profile_email_hint": "អ៊ីមែលមិនអាចផ្លាស់ប្តូរនៅទីនេះ។",
    "edit_profile_bio_placeholder": "ជីវប្រវត្តិខ្លី (ជម្រើស)",
    "edit_profile_phone_hint": "ឧ. ០១២ ៣៤៥ ៦៧៨",
    "edit_profile_city_hint": "ឧ. ភ្នំពេញ សៀមរាប",
    "edit_profile_birth_hint": "ឆ្នាំ-ខែ-ថ្ងៃ",
    "edit_profile_birth_support": "ជម្រើស · ទ្រង់ទ្រាយ 1999-05-20",
    "edit_profile_emergency_hint": "ឈ្មោះ និងទូរស័ព្ទ",
    "edit_profile_emergency_support": "ទំនាក់ទំនងបន្ទាន់សម្រាប់ដំណើរ (ជម្រើស)",
    "btn_save_profile": "រក្សាទុកការផ្លាស់ប្តូរ",
    "label_bio": "ជីវប្រវត្តិខ្លី",
    "label_phone": "លេខទូរស័ព្ទ",
    "label_city": "ទីក្រុងកំណើត/រស់នៅ",
    "label_nationality": "សញ្ជាតិ",
    "label_birth_date": "ថ្ងៃកំណើត",
    "label_gender": "ភេទ",
    "label_travel_style": "ធ្វើដំណើរជាមួយអ្នកណា?",
    "label_emergency_contact": "ទំនាក់ទំនងបន្ទាន់",
    "gender_prefer_not": "មិនចង់បញ្ជាក់",
    "gender_female": "ស្រី",
    "gender_male": "ប្រុស",
    "gender_other": "ផ្សេងទៀត",
    "travel_style_any": "ណាក៏បាន",
    "travel_style_solo": "តែម្នាក់",
    "travel_style_couple": "គូស្នេហ៍",
    "travel_style_family": "គ្រួសារ",
    "travel_style_friends": "មិត្តភ័ក្តិ",
    "settings_section_account": "គណនី និងសុវត្ថិភាព",
    "settings_section_legal": "ផ្លូវច្បាប់ និងគោលការណ៍",
    "settings_section_about": "អំពី",
    "privacy_policy_title": "គោលការណ៍ឯកជនភាព",
    "terms_title": "លក្ខខណ្ឌប្រើប្រាស់",
    "legal_last_updated": "ធ្វើបច្ចុប្បន្នភាពចុងក្រោយ: ឧសភា ២០២៦",
    "legal_intro_privacy": "របៀបដែល Wanderlust គ្រប់គ្រងព័ត៌មានរបស់អ្នកនៅពេលរុករកកន្លែងនៅកម្ពុជា។",
    "legal_intro_terms": "ច្បាប់ប្រើ Wanderlust — កម្មវិធីស្វែងរកកន្លែងឥតគិតថ្លៃសម្រាប់កម្ពុជា (មិនមានការកក់ ឬទូទាត់)។",
    "legal_section_summary": "ចំណុចសំខាន់",
    "legal_highlight_no_sell": "យើងមិនលក់ទិន្នន័យផ្ទាល់ខ្លួនរបស់អ្នក។",
    "legal_highlight_account_data": "អ៊ីមែល ឈ្មោះ និងកន្លែងរក្សាទុកធ្វើសមកាលកម្មពេលចូល។",
    "legal_highlight_location_maps": "ទីតាំងប្រើតែពេលបើកផែនទី — មិនតាមដាននៅផ្ទៃខាងក្រោយ។",
    "legal_highlight_cambodia_only": "ផ្តោតលើកម្ពុជា — បំផុសគំនិតធ្វើដំណើរ មិនមែនកក់សំបុត្រ។",
    "legal_highlight_no_booking": "គ្មានការទូទាត់ សំបុត្រ ឬការកក់ក្នុងកម្មវិធីនេះ។",
    "legal_highlight_sign_in_full": "ចូលដើម្បីមើលបញ្ជីពេញលេញ និងរក្សាទុកកន្លែង។",
    "legal_section_overview": "ទិដ្ឋភាពទូទៅ",
    "legal_privacy_overview": "Wanderlust ជួយអ្នកស្វែងរកប្រាសាទ ឆ្នេរ ភ្នំ និងម្ហូបនៅកម្ពុជា។ គោលការណ៍នេះពន្យល់អ្វីដែលយើងប្រមូល និងមូលហេតុ។",
    "legal_section_data_collect": "អ្វីដែលយើងប្រមូល",
    "legal_privacy_data_collect": "ឈ្មោះគណនី និងអ៊ីមែល (សម្រាប់ចូល) កន្លែងរក្សាទុក និងជីវប្រវត្តិជម្រើស។ យើងមិនប្រមូលព័ត៌មានទូទាត់។",
    "legal_section_data_use": "របៀបប្រើ",
    "legal_privacy_data_use": "ទិន្នន័យប្រើសម្រាប់ចូល បង្ហាញប្រវត្តិរូប និងធ្វើសមកាលកម្មសំណព្វ។ ទីតាំងប្រើតែពេលបើកផែនទី ឬជិតខាង។",
    "legal_section_storage": "ការផ្ទុក និងការចែករំលែក",
    "legal_privacy_storage": "ទិន្នន័យផ្ទុកលើម៉ាស៊ីនបម្រើ PostgreSQL សម្រាប់គម្រោងនេះ។ យើងមិនលក់ព័ត៌មានរបស់អ្នក។",
    "legal_section_rights": "ជម្រើសរបស់អ្នក",
    "legal_privacy_rights": "អ្នកអាចកែឈ្មោះ និងជីវប្រវត្តិក្នុង គណនី → កែប្រវត្តិរូប។ ការផ្លាស់ប្តូរអ៊ីមែលត្រូវការជំនួយ។",
    "legal_terms_overview": "ដោយប្រើ Wanderlust អ្នកយល់ព្រមនឹងលក្ខខណ្ឌទាំងនេះ។ សូមអានមុនពេលចូល ឬរក្សាទុកកន្លែង។",
    "legal_section_terms_service": "សេវាកម្ម",
    "legal_terms_service": "Wanderlust ផ្តល់គំនិតធ្វើដំណើរ និងបញ្ជីកន្លែងរក្សាទុកតែប៉ុណ្ណោះ។ មិនមែនវេទិកាកក់ ឬទូទាត់។",
    "legal_section_terms_account": "គណនីរបស់អ្នក",
    "legal_terms_account": "ចូលដើម្បីប្រើពេញលេញ។ រក្សាពាក្យសម្ងាត់ឱ្យសម្ងាត់។ របៀបភ្ញៀវបង្ហាញតែមើលជាមុន។",
    "legal_section_terms_use": "ការប្រើប្រាស់ដែលទទួលយកបាន",
    "legal_terms_use": "កុំបំពាន API ឬព្យាយាមចូលឧបករណ៍ admin ដោយគ្មានសិទ្ធិ។ មុខងារ admin សម្រាប់គណនីអនុញ្ញាតតែប៉ុណ្ណោះ។",
    "legal_section_terms_changes": "ការផ្លាស់ប្តូរ",
    "legal_terms_changes": "យើងអាចធ្វើបច្ចុប្បន្នភាពទិសដៅ មុខងារ ឬគោលការណ៍ដោយគ្មានជូនដំណឹងជាមុន។ ការបន្តប្រើមានន័យថាអ្នកយល់ព្រម។",
    "legal_footer_note": "មានសំណួរ? ទាក់ទងក្រុមគម្រោង Wanderlust។",
    "about_title": "អំពី Wanderlust",
    "about_version": "កំណែ %1$s",
    "update_available_title": "មានការអាប់ដេត",
    "update_required_title": "ត្រូវការអាប់ដេត",
    "update_available_body": "មានកំណែ Wanderlust ថ្មី៖ %1$s (%2$d)។ ទាញយកនិងដំឡើងលើកម្មវិធីនេះ។",
    "update_download": "ទាញយកការអាប់ដេត",
    "update_later": "ពេលក្រោយ",
    "about_tagline": "ណែនាំកន្លែងនៅកម្ពុជា",
    "about_description": "ស្វែងរកប្រាសាទ ឆ្នេរ ភ្នំ និងម្ហូបនៅកម្ពុជា។ រក្សាទុកកន្លែង មើលបញ្ជី ផែនទី និងអាកាសធាតុ។ គ្មានការកក់ ឬទូទាត់ — តែបំផុសគំនិត។",
    "about_credit": "Wanderlust · កម្ពុជា",
    "about_get_on_devices": "ទាញយកសម្រាប់ Android និង iOS",
    # Common form leftovers
    "label_category": "ប្រភេទ",
    "label_location": "ទីតាំង",
    "label_price_optional": "តម្លៃ (ជម្រើស)",
    "label_duration": "រយៈពេល",
    "profile_help_sub": "សំណួរញឹកញាប់ និងទំនាក់ទំនង",
    "profile_privacy_sub": "របៀបដែលយើងគ្រប់គ្រងទិន្នន័យរបស់អ្នក",
    "profile_terms_sub": "ច្បាប់ប្រើ Wanderlust",
    "settings_privacy_sub": "ការប្រមូល និងប្រើទិន្នន័យ",
    "settings_terms_sub": "លក្ខខណ្ឌប្រើប្រាស់",
}


def esc(s: str) -> str:
    return (
        s.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("'", "\\'")
        .replace('"', '\\"')
    )


def main() -> None:
    text = XML.read_text(encoding="utf-8")
    existing = set(re.findall(r'<string name="([^"]+)">', text))
    base = [k for k in existing if not k.endswith("_kh")]
    missing = [k for k in base if f"{k}_kh" not in existing]

    lines = ["", "    <!-- Auto-generated Khmer pairs (UI language switch) -->"]
    still = []
    for key in sorted(missing):
        kh_key = f"{key}_kh"
        if key not in KH:
            still.append(key)
            continue
        lines.append(f'    <string name="{kh_key}">{esc(KH[key])}</string>')

    # Also add helper keys for hardcoded UI
    extras = {
        "label_category": "Category",
        "label_location": "Location",
        "label_price_optional": "Price label (optional)",
        "label_duration": "Duration",
        "profile_help_sub": "FAQs and contact",
        "profile_privacy_sub": "How we handle your data",
        "profile_terms_sub": "Rules for using Wanderlust",
        "settings_privacy_sub": "Data collection and usage",
        "settings_terms_sub": "Terms of use",
    }
    for en_key, en_val in extras.items():
        if en_key not in existing:
            lines.append(f'    <string name="{en_key}">{esc(en_val)}</string>')
        kh_key = f"{en_key}_kh"
        if kh_key not in existing and en_key in KH:
            lines.append(f'    <string name="{kh_key}">{esc(KH[en_key])}</string>')

    block = "\n".join(lines) + "\n"
    if "</resources>" not in text:
        raise SystemExit("no </resources>")
    XML.write_text(text.replace("</resources>", block + "</resources>"), encoding="utf-8")
    print(f"added kh for {len(missing) - len(still)} keys; still missing translations: {len(still)}")
    if still:
        print("STILL:", ", ".join(still[:40]))


if __name__ == "__main__":
    main()
